# Site settings
title: V秘的平凡之路 -- 最好的视频云制作服务
#author: 多人
# author_avatar: 
email: zhumx@vme360.com
description: 技术blog including git,docker,aliyun,video-making-service,oss,aws,ecs,jenkins,spring-boot,mongodb. 
baseurl: "" # optional
url: "https://videome.github.io/videome.github.io"
#twitter_username: foo_bar
github_username: videome
github_repo: videome/videome.github.io
google_analytics: UA-65584551-3
disqus: videome-blog

# Build settings
paginate: 10
markdown: kramdown
permalink: pretty
excerpt_separator: "<!-- more -->"

colors:
  UmmaTan: '#cfc096'
  BurtonTowerBeige: '#9b9a6d'
  TheRockGray: '#989c97'
  ObservatoryWhite: '#e4e1df'
  AngellHallAsh: '#a79d96'
  LawQuadStone: '#655a52'
  HillBrown: '#7a121c'
  LSAOrange: '#cc6600'
  ArchwayIvy: '#7e732f'
  RackhamRoofGreen: '#83b2a8'
  CanhamPoolBlue: '#587abc'
  MatthaeiViolet: '#575294'
  Blue: '#003366'

authors:
  kane:
    display_name: Kane 
    gravatar: https://www.gravatar.com/avatar/0db85dd6e3b1972fafa2c36e6df3abfb?s=50     
    email: zhumx@vme360.com
    web: https://vme360.com/
    twitter: zxkane
    github: zxkane

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
