# Site settings
title: V秘的平凡之路 -- 最好的视频云制作服务
#author: 多人
# author_avatar: 
email: zhumx@vme360.com
description: 技术blog including git,docker,aliyun,video-making-service,oss,aws,ecs,jenkins,spring-boot,mongodb. 
baseurl: "" # optional
url: "https://videome.github.io/videome.github.io"
#twitter_username: foo_bar
github_username: videome
github_repo: videome/videome.github.io
google_analytics: UA-65584551-3
disqus: videome-blog

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: "<!-- more -->"

authors:
  kane:
    display_name: Kane 
    gravatar: https://www.gravatar.com/avatar/0db85dd6e3b1972fafa2c36e6df3abfb?s=50     
    email: zhumx@vme360.com
    web: https://vme360.com/
    twitter: zxkane
    github: zxkane

gems:
  - jekyll-sitemap
