From ruby:2.4.0

RUN gem sources --add https://gems.ruby-china.org/ --remove https://rubygems.org/ && \
  gem install jekyll:3.0.5 jekyll-sitemap:0.11.0 jekyll-paginate:1.1.0 jekyll-gist:1.4.0 && \
  mkdir /srv/jekyll

EXPOSE 4000
WORKDIR /srv/jekyll
ENTRYPOINT ["jekyll"]
CMD ["serve", "-H", "0.0.0.0", "-P", "4000"]
